version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/backend:cached
      - bundle_data:/usr/local/bundle:cached
      - /backend/node_modules
    ports:
      - "8808:3000"
    links:
      - db
    tty: true
    stdin_open: true
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend/
    image: frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn dev"
    depends_on:
      - backend

  data:
    image: busybox
    volumes:
      - db-data:/var/lib/mysql
    tty: true

volumes:
  db-data:
    driver: local
  bundle_data:
  mysql_data: